USE car_db;

CREATE TABLE IF NOT EXISTS feedback (
    FEEDBACK_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(100),
    RATING INT CHECK (RATING BETWEEN 1 AND 5),
    COMMENT TEXT NOT NULL,
    FEEDBACK_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMAIL) REFERENCES users(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE
);
